name: Multi-Event pipeline / workflow
on:
  push:
    branches:
      - master
      - test

  pull_request:
    branches:
      - master
    

jobs:

  on-push: # New job for push events
    
    runs-on: ubuntu-latest
    steps:
      - name: Running on push
        run: echo "Running on here master/test push"

  on-pull_request:
   
    runs-on: ubuntu-latest
    steps:
      - name: Running on pull requests
        run: echo "Running on pull requests"
  on-game:
    runs-on: ubuntu-latest
    steps:
      - name: Running on game event
        run: echo "Running on game event"

